
#book:
#  #可以直接在yml里面给实体例配置参数
#  name: 三国演义
#  author: 罗贯中
#  price: 30
#  favorites:
#    - 足球
#    - 篮球
#    - 乒乓球
#    - 橄榄球
spring:
  #为了区分开发与线上环境  是通过application-{alias}.yml进行区分的
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB    #设置单个文件的大小
      max-request-size: 100MB   #设置单次请求的文件的总大小
  datasource:
    url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:

#公共配置与profiles选择无关
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.spring.study.entity


multipartUrl:
  path: E:/ProjectTest/multipart/